'use client'

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Copy, Check, Bot } from "lucide-react";
import { ClientToolShell } from "@/components/tools/client-tool-shell";

const COMMON_BOTS = [
  { value: "*", label: "* (all bots)" },
  { value: "Googlebot", label: "Googlebot" },
  { value: "Bingbot", label: "Bingbot" },
  { value: "DuckDuckBot", label: "DuckDuckBot" },
  { value: "Slurp", label: "Slurp (Yahoo)" },
  { value: "Baiduspider", label: "Baiduspider" },
  { value: "YandexBot", label: "YandexBot" },
  { value: "facebookexternalhit", label: "Facebook" },
  { value: "Twitterbot", label: "Twitterbot" },
];

export default function RobotsTxtGenerator() {
  const [allowAll, setAllowAll] = useState<boolean>(true);
  const [sitemapUrl, setSitemapUrl] = useState<string>("https://example.com/sitemap.xml");
  const [disallowRaw, setDisallowRaw] = useState<string>("/admin/\n/private/\n/cart/");
  const [crawlDelay, setCrawlDelay] = useState<string>("");
  const [userAgent, setUserAgent] = useState<string>("*");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const lines: string[] = [];

    if (allowAll) {
      lines.push("User-agent: *");
      lines.push("Allow: /");
      // Still emit any explicit disallow blocks as additional rules
      const paths = parsePaths(disallowRaw);
      if (paths.length) {
        lines.push("");
        lines.push("# Additional disallow rules");
        lines.push(`User-agent: ${userAgent === "*" ? "*" : userAgent}`);
        for (const p of paths) lines.push(`Disallow: ${p}`);
      }
    } else {
      const paths = parsePaths(disallowRaw);
      lines.push(`User-agent: ${userAgent}`);
      if (paths.length === 0) {
        lines.push("Disallow: /");
      } else {
        for (const p of paths) lines.push(`Disallow: ${p}`);
      }
    }

    if (crawlDelay.trim()) {
      const n = parseFloat(crawlDelay);
      if (isFinite(n) && n >= 0) {
        lines.push(`Crawl-delay: ${n}`);
      }
    }

    if (sitemapUrl.trim()) {
      lines.push("");
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    lines.push("");
    lines.push("# Generated by NexTool Robots.txt Generator");
    return lines.join("\n");
  }, [allowAll, sitemapUrl, disallowRaw, crawlDelay, userAgent]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* ignore */ }
  };

  return (
    <ClientToolShell>
      <div className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          <Label>Crawler policy:</Label>
          <Button
            size="sm"
            variant={allowAll ? "default" : "outline"}
            onClick={() => setAllowAll(true)}
          >
            Allow all
          </Button>
          <Button
            size="sm"
            variant={!allowAll ? "default" : "outline"}
            onClick={() => setAllowAll(false)}
          >
            Restrict
          </Button>
        </div>

        {!allowAll && (
          <div className="space-y-1.5">
            <Label htmlFor="rb-ua">User-agent to restrict</Label>
            <Input
              id="rb-ua"
              value={userAgent}
              onChange={(e) => setUserAgent(e.target.value)}
              placeholder="* or specific bot"
            />
            <div className="flex flex-wrap gap-1.5">
              {COMMON_BOTS.map((b) => (
                <button
                  key={b.value}
                  type="button"
                  onClick={() => setUserAgent(b.value)}
                  className="rounded-full border bg-card px-2.5 py-0.5 text-xs hover:bg-muted transition"
                >
                  {b.label}
                </button>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-1.5">
          <Label htmlFor="rb-disallow">Disallow paths (one per line)</Label>
          <Textarea
            id="rb-disallow"
            rows={5}
            value={disallowRaw}
            onChange={(e) => setDisallowRaw(e.target.value)}
            placeholder={"/admin/\n/private/\n/cgi-bin/"}
            className="font-mono text-sm"
          />
          <p className="text-xs text-muted-foreground">
            Use trailing slash to block a directory, e.g. <code>/admin/</code>.
            Use a path with extension to block a specific file, e.g. <code>/private.pdf</code>.
          </p>
        </div>

        <div className="grid gap-3 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor="rb-sitemap">Sitemap URL</Label>
            <Input
              id="rb-sitemap"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="https://example.com/sitemap.xml"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="rb-delay">Crawl-delay (seconds, optional)</Label>
            <Input
              id="rb-delay"
              type="number"
              min={0}
              step="any"
              value={crawlDelay}
              onChange={(e) => setCrawlDelay(e.target.value)}
              placeholder="10"
            />
          </div>
        </div>

        <div>
          <div className="mb-2 flex items-center justify-between">
            <p className="flex items-center gap-1.5 text-sm font-medium">
              <Bot className="h-4 w-4" /> robots.txt
              <Badge variant="secondary" className="ml-1">{output.length} chars</Badge>
            </p>
            <Button size="sm" variant="outline" onClick={copy} className="gap-1.5">
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
          <pre className="max-h-80 overflow-auto rounded-lg bg-muted p-3 text-xs font-mono leading-relaxed">
{output}
          </pre>
        </div>

        <p className="text-xs text-muted-foreground">
          Place the generated file at the root of your domain, e.g.
          <code className="mx-1">https://example.com/robots.txt</code>.
          Bots are not legally required to honor directives — malicious crawlers may ignore them.
        </p>
      </div>
    </ClientToolShell>
  );
}

function parsePaths(raw: string): string[] {
  return raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}
